name: .NET Core
on:
  push:
    branches: [ master ]
  pull_request:
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: Component.ServicesDescriptor
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          source-url: https://nuget.pkg.github.com/Chac-Bolay/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Extract Branch Name
        if: matrix.os == 'ubuntu-latest'
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Pack
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master' 
        run: |
          export VERSION=0.0.$GITHUB_RUN_ID
          if [ ${{ steps.extract_branch.outputs.branch }} != 'master' ];
            then
              VERSION=0.0.$GITHUB_RUN_ID.${{ steps.extract_branch.outputs.branch }}
            else
              VERSION=0.0.$GITHUB_RUN_ID
            fi
          dotnet pack -v normal -c Release --no-restore -p:PackageVersion=$VERSION -o ${{github.workspace}}/nupkg
      - name: Publish
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
        run: dotnet nuget push ${{github.workspace}}/nupkg/*.nupkg --skip-duplicate --no-symbols true
